### ISSUE TITLE
NEMO: Replace RPIO.GPIO with pigpio

### ISSUE THREAD

**Issue by tmf97** [Cislunar-Explorers/FlightSoftware#43]
We are no longer using the RPI.GPIO library for controlling the GPIO pins, for timing reasons. 
I'm not sure how using two different libraries to control GPIO outputs would clash (if at all). If you have reason to believe it's not an issue - please let me know!

pigpio: http://abyz.me.uk/rpi/pigpio/python.html
`pip3 install pigpio`

The syntax between the two libraries are very similar.
With `pi = pigpio.pi()` 
`GPIO.setup(channel, GPIO.IN)` is now `pi.set_mode(channel, pigpio.INPUT)`
`GPIO.output(channel, GPIO.HIGH)` is now `pi.write(channel, 1)`
etc...

**Comment by matthewlh** [comment]
Ok, I'll get the nemo code switched over to pigpio for GPIO access.

It looks like you're using both pigpio and busio for I2C, is there a preference which should be used for nemo?

**Comment by tmf97** [comment]
I have a very slight preference for busio for Nemo's i2c because that's what most of our other sensors use. The only reason we're using pigpio for i2c is because of that specific driver's heritage.

**Comment by matthewlh** [comment]
Copy that, I'll stick with busio then.

**Comment by matthewlh** [comment]
Resolved in a5fad5a3c81f96b0495f382b54550d13f383a367
